version: '3'
services:
  admin-app:
    container_name: admin-app
    restart: always
    build: ../admin-app/.
    ports:
      - '8080:8080'
    links:
      - api-server
  api-server:
    container_name: api-server
    environment: 
      - MONGODB_URL=mongodb://mongo/admin
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    expose:
      - '27017'
